### ISSUE TITLE
Question Ancular Cli

### ISSUE THREAD

**Issue by stekontar** [fgladisch/angular2-webpack-seed#1]
Hello @fgladisch . 
Firstly I would like to thank you for this seed project. It really saves me a lot of time.
May I ask if this functionality could be applied on an angular/cli (version 1.3.1) project? 
Is it possible to create a new brunch? (if it is not took you much time)

Regards,
S.

**Comment by fgladisch** [comment]
Hi @stekontar,

Angular CLI has a lot in common with this project in terms of features. However, I'm afraid that it's not directly compatible with it. You can think of it as an alternative to Angular CLI for developers, who want to be in control of the project environment. You can not directly use the CLI features in this project.

What you **can** do is: 

- Run `ng eject` (described [here](https://github.com/angular/angular-cli/wiki/eject)) in a Angular CLI project and replace/edit some of the configuration files according to this project. 

- Run `ng init` with and older version of Angular CLI (it was removed in a recent release) in this project and follow the instructions. You can remove the `config` folder and some of the configuration files after that.

**Comment by stekontar** [comment]
Thank you very much for your response.
