### ISSUE TITLE
changing bundled file path in html file

### ISSUE THREAD

**Issue by kumaresan-subramani** [fgladisch/angular2-webpack-seed#5]
**if i moved html file from dist folder to outside  using following gulp task, how can i change the path of bundled file in html**
**which means, in here how can i change path of ts and css files**

> <script type="text/javascript" src="polyfills.e6b85da4b9b36d023c5e.js"></script><script type="text/javascript" src="app.e6b85da4b9b36d023c5e.js"></script><script type="text/javascript" src="ts-file.e6b85da4b9b36d023c5e.js"></script></body>
 
_ <link rel="shortcut icon" href="favicon.ico"><link href="app.e6b85da4b9b36d023c5e.css" rel="stylesheet"></head>_
**gulp task to move html file**
`var filesToMove = [
    'dist/index.html',
    ];

gulp.task('move', function(){
// the base option sets the relative root for the set of files,
// preserving the folder structure
gulp.src(filesToMove, { base: './' })
.pipe(gulp.dest('./'));
});`

**Comment by fgladisch** [comment]
I'm not sure what you are trying to achieve. I would not recommend to use gulp in a webpack project. You can change the output path for your build files [in this line](https://github.com/fgladisch/angular2-webpack-seed/blob/master/config/webpack.prod.js#L15).

**Comment by kumaresan-subramani** [comment]
@fgladisch , hi i want change my bundled html file location
only html file not all bundled file, if i change that line all files were moved not  only html file
